"""
create_xml_ticket.py — Génération de tickets XML pour PrimeCenter
Projet: PrintFlow SaaS — PrimeCenter Integration
Version: 1.0 — Fév 2026

Génère les tickets XML d'entrée (pour PrimeCenter MAX futur)
et lit/parse les tickets XML de sortie (générés par PrimeCenter PRO/MAX).

Usage:
    python create_xml_ticket.py 012345_001_Vitrine_Orange02_1210x650mm_20ex.pdf
    python create_xml_ticket.py --parse output_ticket.xml
    python create_xml_ticket.py --batch "\\\\\\\\nas\\\\dossier\\\\01_INPUT_FILES"
"""

import os
import sys
import json
import re
from pathlib import Path
from datetime import datetime
from xml.etree import ElementTree as ET
from xml.dom import minidom

# Import du parser de nomenclature (dans le même dossier)
sys.path.insert(0, str(Path(__file__).parent))
from parse_nomenclature import parse_filename, JobMetadata


# ============================================================
# CHEMINS NAS (à adapter selon votre infrastructure)
# ============================================================

NAS_BASE = r"\\obelix_nascp\Boite de transferts\KARIM\PRIMECENTER\TEST Mise en place"

DOSSIERS_NAS = {
    "input":       fr"{NAS_BASE}\01_INPUT_FILES",
    "bat_output":  fr"{NAS_BASE}\02_OUTPUT_PREFLIGHT_FIXUP",
    "prod_output": fr"{NAS_BASE}\02_PROD_PREFLIGHT_FIXUP",
    "bat_ctrl":    fr"{NAS_BASE}\03_BAT_CTRL_PREFLIGHT",
    "prod_input":  fr"{NAS_BASE}\03_PROD_PREFLIGHT_INPUT",
    "cut_files":   fr"{NAS_BASE}\04 - OUTPUT_CUTFILES",
    "print_files": fr"{NAS_BASE}\04 - OUTPUT_PRINTFILES",
    "recipes":     fr"{NAS_BASE}\05 - RECIPES",
    "rapports":    fr"{NAS_BASE}\06 - RAPPORTS PRIMECENTER",
}

# Convertit le chemin Windows UNC en format URL pour XML
def unc_to_url(unc_path: str) -> str:
    """Convertit chemin UNC Windows en URL file:// pour XML PrimeCenter."""
    # \\server\share\folder → file:////server/share/folder
    clean = unc_path.replace("\\", "/")
    if clean.startswith("//"):
        return f"file:{clean}"
    elif clean.startswith("/"):
        return f"file://{clean}"
    else:
        return f"file:///{clean}"


# ============================================================
# GÉNÉRATION TICKET XML D'ENTRÉE
# ============================================================

def creer_ticket_xml_entree(
    metadata: JobMetadata,
    mode: str = "bat",
    include_preflight: bool = True
) -> str:
    """
    Génère un ticket XML d'entrée pour PrimeCenter.
    (Utilisé principalement pour PrimeCenter MAX futur)
    En PRO: utile pour documentation et futur upgrade.

    Args:
        metadata:          JobMetadata extrait du nom de fichier
        mode:              'bat' ou 'prod'
        include_preflight: Inclure la section preflight

    Returns:
        Contenu XML formaté (string)
    """
    # Chemin du fichier source
    input_file = f"{DOSSIERS_NAS['input']}\\{metadata.filename}"
    input_url = unc_to_url(input_file)

    # Heure de création
    now = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

    # Créer l'arbre XML
    ticket = ET.Element("ticket", version="1")

    # --- PARTIE JOB ---
    job = ET.SubElement(ticket, "job", creationTime=now)

    # Source
    source = ET.SubElement(job, "source")
    ET.SubElement(source, "filespec").text = input_url
    ET.SubElement(source, "pages").text = "1"
    ET.SubElement(source, "copies").text = str(metadata.copies)

    # Media (dimensions du visuel — sans fond perdu)
    media = ET.SubElement(job, "media")
    ET.SubElement(media, "width", unit="mm").text = str(metadata.width_mm)
    ET.SubElement(media, "height", unit="mm").text = str(metadata.height_mm)

    # Process (recette + ganging)
    process = ET.SubElement(job, "process")
    ET.SubElement(process, "recipe").text = metadata.recette
    # Ganging par matière (gangName = customerID dans PrimeCenter)
    gang = ET.SubElement(process, "gang")
    gang.set("by", "customerID")

    # Info (métadonnées)
    info = ET.SubElement(job, "info")
    ET.SubElement(info, "orderID").text = metadata.order_id
    ET.SubElement(info, "jobID").text = metadata.job_id
    ET.SubElement(info, "jobName").text = metadata.job_name
    # gangName → customerID (utilisé pour grouper par matière)
    ET.SubElement(info, "customerID").text = metadata.gang_name
    ET.SubElement(info, "comment").text = f"Mode:{mode.upper()} | AutoGenerated:{now[:10]}"

    # Preflight (optionnel)
    if include_preflight:
        preflights = ET.SubElement(job, "preflights")
        pf1 = ET.SubElement(preflights, "preflight1")
        ET.SubElement(pf1, "profile").text = "Verify_Colors_Resolution_Fonts"
        pf2 = ET.SubElement(preflights, "preflight2")
        ET.SubElement(pf2, "profile").text = "Fix_RGB_CMYK_FontEmbedding"

    # Formater en XML lisible
    xml_str = ET.tostring(ticket, encoding="unicode")
    dom = minidom.parseString(xml_str)
    return dom.toprettyxml(indent="  ", encoding=None).replace(
        '<?xml version="1.0" ?>', '<?xml version="1.0" encoding="UTF-8"?>'
    )


# ============================================================
# LECTURE TICKET XML DE SORTIE
# ============================================================

def lire_ticket_sortie(xml_path: str) -> dict:
    """
    Parse un ticket XML de sortie généré par PrimeCenter.
    Extrait les informations utiles pour le dashboard et l'Agent LLM.

    Args:
        xml_path: Chemin vers le fichier XML de sortie

    Returns:
        Dictionnaire avec toutes les informations extraites
    """
    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()
    except ET.ParseError as e:
        return {"erreur": f"XML invalide: {e}"}

    result = {
        "version": root.get("version", "?"),
        "last_event": root.get("lastEvent", ""),
        "jobs": [],
        "layouts": []
    }

    # Parser chaque job
    for job in root.findall("job"):
        job_data = {
            "creation_time": job.get("creationTime", ""),
            "source": {},
            "media": {},
            "process": {},
            "info": {}
        }

        # Source
        source = job.find("source")
        if source is not None:
            filespec = source.findtext("filespec", "")
            job_data["source"] = {
                "filespec": filespec,
                "pages": source.findtext("pages", "1"),
                "copies": source.findtext("copies", "1")
            }

        # Media
        media = job.find("media")
        if media is not None:
            w = media.find("width")
            h = media.find("height")
            job_data["media"] = {
                "width_mm": w.text if w is not None else "",
                "height_mm": h.text if h is not None else ""
            }

        # Process
        process = job.find("process")
        if process is not None:
            job_data["process"] = {
                "recipe": process.findtext("recipe", ""),
                "gang": process.findtext("gang", "")
            }

        # Info
        info = job.find("info")
        if info is not None:
            job_data["info"] = {
                "order_id": info.findtext("orderID", ""),
                "job_id": info.findtext("jobID", ""),
                "job_name": info.findtext("jobName", ""),
                "customer_id": info.findtext("customerID", ""),
                "comment": info.findtext("comment", "")
            }

        result["jobs"].append(job_data)

    # Parser chaque layout (amalgame)
    for layout in root.findall("layout"):
        layout_data = {
            "name": layout.get("name", ""),
            "last_event": layout.get("lastEvent", ""),
            "info": {},
            "paths": {},
            "jobs_contents": []
        }

        # Info amalgame
        info = layout.find("info")
        if info is not None:
            stats = info.find("stats")
            layout_data["info"] = {
                "fill_ratio": info.findtext("fillRatio", ""),
                "area_m2": stats.findtext("area") if stats is not None else "",
                "waste_m2": stats.findtext("waste") if stats is not None else "",
                "media_name": info.findtext("mediaName", ""),
                "gang": info.findtext("gang", ""),
                "width_mm": info.findtext("width", ""),
                "height_mm": info.findtext("height", ""),
                "cropped": info.findtext("cropped", "false")
            }

        # Chemins fichiers générés
        paths = layout.find("paths")
        if paths is not None:
            output = paths.find("output")
            cut = paths.find("cut")
            layout_data["paths"] = {
                "print_file": output.text.strip() if output is not None else "",
                "cut_file": cut.text.strip() if cut is not None else "",
                "print_timestamp": output.get("timeStamp", "") if output is not None else "",
                "cut_timestamp": cut.get("timeStamp", "") if cut is not None else ""
            }

        # Contenu (positions des visuels)
        contents = layout.find("contents")
        if contents is not None:
            for job_in_layout in contents.findall("job"):
                job_content = {
                    "id": job_in_layout.get("id", ""),
                    "items": job_in_layout.get("items", ""),
                    "positions": []
                }
                for item in job_in_layout.findall("item"):
                    job_content["positions"].append({
                        "page": item.get("page", "1"),
                        "x": item.get("x", "0"),
                        "y": item.get("y", "0"),
                        "w": item.get("w", "0"),
                        "h": item.get("h", "0"),
                        "angle": item.get("angle", "0")
                    })
                layout_data["jobs_contents"].append(job_content)

        result["layouts"].append(layout_data)

    return result


# ============================================================
# WORKFLOW COMPLET: FILENAME → XML → NAS
# ============================================================

def traiter_fichier(
    filename: str,
    mode: str = "bat",
    sauvegarder: bool = True
) -> dict:
    """
    Workflow complet: parse le filename, crée le ticket XML, le sauvegarde.

    Args:
        filename:   Nom du fichier (ex: '012345_001_Vitrine_Orange02_1210x650mm_20ex.pdf')
        mode:       'bat' ou 'prod'
        sauvegarder: Sauvegarder le XML dans les rapports?

    Returns:
        {'success': bool, 'metadata': dict, 'xml_path': str, 'xml_content': str}
    """
    # 1. Extraire les métadonnées
    meta = parse_filename(filename)
    if not meta.valide:
        return {"success": False, "erreur": meta.erreur}

    # 2. Générer le ticket XML
    xml_content = creer_ticket_xml_entree(meta, mode=mode)

    # 3. Nom du fichier XML de sortie
    xml_filename = filename.replace(meta.extension, "_ENTREE.xml")
    xml_path = ""

    # 4. Sauvegarder dans les rapports
    if sauvegarder:
        date_str = datetime.now().strftime("%Y-%m-%d")
        rapport_dir = Path(DOSSIERS_NAS["rapports"]) / date_str

        try:
            rapport_dir.mkdir(parents=True, exist_ok=True)
            xml_path = str(rapport_dir / xml_filename)
            with open(xml_path, "w", encoding="utf-8") as f:
                f.write(xml_content)
            print(f"[OK] Ticket XML sauvegardé: {xml_path}")
        except Exception as e:
            print(f"[ATTENTION] Impossible de sauvegarder XML: {e}")
            print(f"[INFO] XML généré (non sauvegardé):\n{xml_content}")

    return {
        "success": True,
        "metadata": {
            "order_id": meta.order_id,
            "job_id": meta.job_id,
            "job_name": meta.job_name,
            "gang_name": meta.gang_name,
            "width_mm": meta.width_mm,
            "height_mm": meta.height_mm,
            "copies": meta.copies,
            "recette": meta.recette
        },
        "xml_path": xml_path,
        "xml_content": xml_content
    }


# ============================================================
# CLI
# ============================================================

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)

        # Test interne
        print("\n--- TEST: Création ticket XML d'entrée ---")
        result = traiter_fichier(
            "012345_001_Vitrine_Orange02_1210x650mm_20ex.pdf",
            mode="bat",
            sauvegarder=False
        )
        if result["success"]:
            print(f"Métadonnées: {json.dumps(result['metadata'], indent=2)}")
            print(f"\nXML généré:\n{result['xml_content']}")

        print("\n--- TEST: Parse ticket XML de sortie (simulé) ---")
        # Créer un XML de test temporaire
        test_xml = """<?xml version="1.0" encoding="UTF-8"?>
<ticket version="1" lastEvent="2026-02-17T15:00:00">
  <job creationTime="2026-02-17T14:30:00">
    <source>
      <filespec>file:////nas/01_INPUT/012345_001_Vitrine_Orange02_1210x650mm_20ex.pdf</filespec>
      <copies>20</copies>
    </source>
    <media>
      <width unit="mm">1210</width>
      <height unit="mm">650</height>
    </media>
    <info>
      <orderID>012345</orderID>
      <jobID>001</jobID>
      <jobName>Vitrine</jobName>
      <customerID>Orange02</customerID>
    </info>
  </job>
  <layout name="Nest_Orange02_001" lastEvent="2026-02-17T15:00:00">
    <info>
      <fillRatio>78</fillRatio>
      <stats>
        <area unit="m2">1.573</area>
        <waste unit="m2">0.441</waste>
      </stats>
      <mediaName>Orange02</mediaName>
      <width>1300.000000</width>
      <height>1870.000000</height>
    </info>
    <paths>
      <output timeStamp="2026-02-17T15:00:00">file:////nas/04_PRINT/012345_001_PRINT.pdf</output>
      <cut timeStamp="2026-02-17T15:00:00">file:////nas/04_CUT/012345_001_CUT.zcc</cut>
    </paths>
    <contents>
      <job id="001" items="20">
        <item page="1" x="100.0" y="50.0" w="1220.0" h="660.0" angle="0"/>
      </job>
    </contents>
  </layout>
</ticket>"""

        # Écrire temporairement et parser
        test_path = "test_output_ticket.xml"
        with open(test_path, "w", encoding="utf-8") as f:
            f.write(test_xml)

        parsed = lire_ticket_sortie(test_path)
        print(f"Ticket parsé: {json.dumps(parsed, indent=2, ensure_ascii=False)}")

        os.remove(test_path)
        sys.exit(0)

    # Mode --parse
    if sys.argv[1] == "--parse":
        if len(sys.argv) < 3:
            print("Erreur: Spécifier le fichier XML à parser")
            sys.exit(1)
        result = lire_ticket_sortie(sys.argv[2])
        print(json.dumps(result, indent=2, ensure_ascii=False))

    # Mode fichier unique
    else:
        mode = "bat"
        if "--prod" in sys.argv:
            mode = "prod"
        result = traiter_fichier(sys.argv[1], mode=mode, sauvegarder=True)
        if result["success"]:
            print(f"[OK] Ticket créé: {result['xml_path']}")
            print(f"Métadonnées: {json.dumps(result['metadata'], indent=2)}")
        else:
            print(f"[ERREUR] {result['erreur']}")
            sys.exit(1)
